### ISSUE TITLE
erro| 'svelte/internal' does not contain an export named 'validate_slots'

### ISSUE THREAD

**Issue by st-clair-clarke** [tjinauyeung/svelte-forms-lib#11] opened 2020-03-11 10:31 UTC
**Describe the bug**
I have a class Name.svelte with a "@smui/textfield": "^1.0.0-beta.20", as shown below:
*NB*
1. ***Using [sapper-smui-typescript-template](https://github.com/manuel3108/sapper-smui-typescript-template)***

2. **<script lang='typescript'>** MUST be as is - no formatting spaces or error out.

```
<script lang='typescript'>
  import Textfield from '@smui/textfield'
  import {createForm} from 'svelte-forms-lib';
  import * as yup from 'yup'
  import HelperText from '@smui/textfield/helper-text/index';

  const {
    form, errors, state, touched, isValid, isSubmitting,
    isValidating, handleBlur, handleChange, handleSubmit
  } = createForm({
    initialValues: {
      title: '',
      name: '',
      email: ''
    },
    validationSchema: yup.object().shape({
      name: yup.string().required(),
      email: yup.string().email().required()
    }),

    onSubmit: values => {
      alert(JSON.stringify(values));
    }
  });

</script>

<form class:valid = {$isValid}
      on:submit = {handleSubmit}>

  <div>
    <Textfield id = 'email'
               name = 'email'
               type = 'email'
               label = 'Email'
               on:change = {handleChange}
               bind:value = {$form.email}/>    {#if $errors.email && $touched.email}
    <HelperText validationMsg>{$errors.email}</HelperText>    {/if}  </div>
  <div>{$errors.email}</div>
</form>

```

Running the app results in the following console output without the validation message being displayed, although the textfield colour changes to red and the appropriate hover message on the textfields.

```
node_modules/svelte-forms-lib/lib/components/Form.svelte 142:1-15
" 'svelte/internal' does not contain an export named 'validate_slots'.
node_modules/svelte-forms-lib/lib/components/Field.svelte 101:1-15
" 'svelte/internal' does not contain an export named 'validate_slots'.
node_modules/svelte-forms-lib/lib/components/Select.svelte 128:1-15
" 'svelte/internal' does not contain an export named 'validate_slots'.
node_modules/svelte-forms-lib/lib/components/ErrorMessage.svelte 142:1-15
" 'svelte/internal' does not contain an export named 'validate_slots'.
✔ service worker (30ms)
> Listening on http://localhost:3000
```

**To Reproduce**
Copy Name.svelte and run, Listening on http://localhost:3000

**Expected behavior**
Error to be displayed as per docs

**Screenshots**
**Chrome**
![image](https://user-images.githubusercontent.com/3227590/76406406-e6d80a00-6346-11ea-9ad2-6e02d2efc358.png)

**Firefox**
![image](https://user-images.githubusercontent.com/3227590/76406659-5221dc00-6347-11ea-89cf-e73f9f5453b4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (most recent updates)
 - Browser [chrome, firefox] - others not checked
 - Version [chrome: Version 82.0.4082.0 (Official Build) canary (64-bit); firefox: 73.0.1 (64bit) ]

**Additional context**
***Using [sapper-smui-typescript-template](https://github.com/manuel3108/sapper-smui-typescript-template)***

**Comment by 77MohKam88** [comment] 2020-05-16 14:51
I have this issue too. Any fix ?

**Comment by tiaanduplessis** [comment] 2020-07-14 20:35
This issue appears to be related to https://github.com/rixo/svelte-template-hot/issues/3

Svelte needs to be deduped. Adding a Webpack alias for resolution of the module appears to be a temporary workaround:

```
resolve: { 
			extensions, 
			mainFields, 
			alias: {
				svelte: path.resolve(__dirname, 'node_modules/svelte')
			}
		},
```

An example using sapper-smui-typescript-template can be seen here: https://github.com/tiaanduplessis/svelte-form-lib-issue-11

@tjinauyeung @larrybotha I think the cause of this issue may be Svelte being listed as a dependency instead of a dev dependency.

**Comment by larrybotha** [comment] 2020-07-16 02:20
@tiaanduplessis I've seen something about installing Svelte as a dev dep for npm modules; with a quick search I only found this one: https://dev.to/agustinl/creating-a-package-for-svelte-262n, and couldn't find anything meaningful in Svelte's issues.

Does installing Svelte as a dev dep fix the issue?

**Comment by tiaanduplessis** [comment] 2020-07-16 11:26
@larrybotha yeah I don't think the issue is too common since the default Svelte template handles the deduping (https://github.com/sveltejs/sapper-template/blob/master/webpack.config.js#L9), but moving it will help prevent future issues.

**Comment by tiaanduplessis** [comment] 2020-07-16 11:52
@st-clair-clarke can you confirm if adding the appropriate alias to the webpack config resolves for you as well?

**Comment by larrybotha** [comment] 2021-03-06 20:20
Closing this issue. Feel free to open if the issue persists.

**Closed by larrybotha** 2021-03-06 20:20 UTC
